[package]
name = "orbrs"
version = "0.1.0"
authors = ["patrickisroman <>"]
edition = "2021"

[profile.release]
opt-level = 3

[dependencies]
image = "0.25.5"
imageproc = "*"
rand = "0.8.5"
bitvector = "0.1.5"
cgmath = "0.18.0"

